#!/bin/sh

### BEGIN INIT INFO
# Provides:          afterboot
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts something after boot
# Description:       starts something using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
. /lib/lsb/init-functions
MYDISKS=$(ls -l /dev/disk/by-uuid | grep /sd.1 | tr -s ' ' | cut -d " " -f 9)

#echo ${MYDISKS} $1

case "$1" in
       start)
                for DISK in ${MYDISKS}
                do
                  echo ${DISK}
                  if [ -e /dev/disk/by-uuid/${DISK} ]; then
                    echo -n "[....] Mount /mnt/${DISK}: "
                    if [ ! -d /mnt/${DISK} ]; then
                      mkdir -p /mnt/${DISK}
                    fi
                    mount /dev/disk/by-uuid/${DISK} /mnt/${DISK}
                    log_end_msg $?
                    sleep 2
                  fi
                done
                sleep 2
                /etc/init.d/sensorhub start
		/etc/init.d/mysql start
                /etc/init.d/samba start
               ;;
       stop)
                /etc/init.d/samba stop
                sleep 2
                for DISK in ${MYDISKS}
                do
                  if [ -e /dev/disk/by-uuid/${DISK} ]; then
                    echo -n "[....] Unmount /${DISK}: "
                    umount /${DISK}
                    log_end_msg $?
                    sleep 2
                  fi
		  if [ -d /mnt/${DISK} ]; then
                    rmdir /mnt/${DISK}
                    log_end_msg $?
                  fi
                done
               ;;
       status)
               df -h | grep /netz
               /etc/init.d/samba status
               ;;
       *)
               echo "Usage: $NAME {start|stop|status}" >&2
               exit 1
               ;;
esac

exit 0


